### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by FKXshadow** [revanced/revanced-website#96] opened 2023-06-06 06:05 UTC
![Screenshot_2023-06-06-09-02-04-20_d365b52accad0f47adbc08c16219827d.jpg](https://github.com/revanced/revanced-website/assets/83650658/404fe5ea-86dc-410a-a189-e66ff9a8a44c)

**Comment by xafn** [comment] 2023-06-06 06:06
Duplicate of #95

**Comment by oSumAtrIX** [comment] 2023-06-06 06:06
Currently an issue with deployment and outside of our reach, probably have to wait some minutes

**Closed** 2023-06-06 06:06 UTC

**Comment by FKXshadow** [comment] 2023-06-06 06:10
Sure, I'll wait. Just wanted the developers to know about it.
