### ISSUE TITLE
Website has no "no script" warning

### ISSUE THREAD

**Issue by EhabxAlaa** [revanced/revanced-website#119] opened 2023-06-10 21:14 UTC
![IMG_20230611_000453](https://github.com/revanced/revanced-website/assets/120474122/0e89ff0d-f48e-4a08-91aa-95c1b4671c36)
This button doesn't work when you are at the homepage but works fine everywhere else

**Comment by oSumAtrIX** [comment] 2023-06-10 21:17
Can not reproduce:

https://github.com/revanced/revanced-website/assets/13122796/162552c7-4d70-4526-88e9-5e066dd631a4

**Comment by Julius8900** [comment] 2023-06-10 21:18
> ![IMG_20230611_000453](https://user-images.githubusercontent.com/120474122/244895014-0e89ff0d-f48e-4a08-91aa-95c1b4671c36.jpg) This button doesn't work when you are at the homepage but works fine everywhere else

Send a recording when this problem happens.

**Comment by EhabxAlaa** [comment] 2023-06-10 21:22
I will try in a different browser first if it doesn't work i will record a video

**Comment by EhabxAlaa** [comment] 2023-06-10 21:26
So i tried in a different browser "brave" and it had way more issues like the patches page does not open , i just get a blank page and this button does not work on any page and many more issues, so what should i do?

**Comment by EhabxAlaa** [comment] 2023-06-10 21:29
Also you can't download manager, you only get view source like this 
![Screenshot_2023-06-11-00-29-05-980_com brave browser](https://github.com/revanced/revanced-website/assets/120474122/dd18d064-45fe-4705-9575-d7bf352f4ae3)

**Comment by oSumAtrIX** [comment] 2023-06-10 21:30
I can not reproduce any of these issues, try on chrome

**Comment by EhabxAlaa** [comment] 2023-06-10 21:30
> I can not reproduce any of these issues, try on chrome

I deleted it 🙂

**Comment by EhabxAlaa** [comment] 2023-06-10 21:31
I will try on all browser i have

**Comment by oSumAtrIX** [comment] 2023-06-10 21:32
> > I can not reproduce any of these issues, try on chrome
> 
> I deleted it 🙂

Install it 🙂

**Comment by EhabxAlaa** [comment] 2023-06-10 21:34
> > > I can not reproduce any of these issues, try on chrome
> > 
> > 
> > I deleted it 🙂
> 
> Install it 🙂

Damn it,  i had to go through a lot to delete it completely ( not much really) but sure i will do it for you 🙂

**Comment by EhabxAlaa** [comment] 2023-06-10 21:38
So chrome obviously had the same issues as brave and here is a  screenshot  of one issue 
![Screenshot_2023-06-11-00-37-07-443_com android chrome](https://github.com/revanced/revanced-website/assets/120474122/89038b2f-b4e2-410e-9d18-ebf932a2862a)

**Comment by EhabxAlaa** [comment] 2023-06-10 21:39
The first browser that had only the first issue was Samsung browser btw

**Comment by oSumAtrIX** [comment] 2023-06-10 21:46
Attach a debugger to Chrome or use the inbuilt dev console in Kiwi browser and log exceptions in the console

**Comment by EhabxAlaa** [comment] 2023-06-10 21:46
I tried two more browsers and one has the same issues as brave and chrome and the other had the same issue as Samsung browser, do you need recording for them?

**Comment by oSumAtrIX** [comment] 2023-06-10 21:47
I need you to check the logs for exceptions as described above

**Comment by EhabxAlaa** [comment] 2023-06-10 21:48
> I need you to check the logs for exceptions as described above
Ok how so i attach a debuger to chrome?

**Comment by Aunali321** [comment] 2023-06-10 21:48
/patches is blank for me on chrome mobile

**Comment by oSumAtrIX** [comment] 2023-06-10 21:49
Can not reproduce. Check the logs
![image](https://github.com/revanced/revanced-website/assets/13122796/eb153f8f-df3f-4a11-b5bf-fe0bc7531e6a)

**Comment by EhabxAlaa** [comment] 2023-06-10 21:49
> /patches is blank for me on chrome mobile

Yup same and there are other issues too please check as i have an exam and need to study🥲

**Comment by EhabxAlaa** [comment] 2023-06-10 21:54
Try these browsers on mobile and you will be able to check the logs or whatever you want to do by yourself since i have no idea on how to do that

**Comment by EhabxAlaa** [comment] 2023-06-10 21:57
So Samsung browser and SnapTube had the home button issue only and the other three ( brave, chrome, ADM browser) had multiple issues like the hamburger menu not working on any page, the patches page is empty and can't download manager, maybe there is more too)

**Comment by EhabxAlaa** [comment] 2023-06-10 22:06
So one more thing does this  settings button normally function? As i tried it on pc and it didn't do anything 
![IMG_20230611_010512](https://github.com/revanced/revanced-website/assets/120474122/a5141a4a-25ce-4fde-84b9-321779aa00d2)

**Comment by Ushie** [comment] 2023-06-10 22:07
can you do ctrl dev i and show the console after clicking the button?

**Comment by EhabxAlaa** [comment] 2023-06-10 22:08
> can you do ctrl dev i and show the console after clicking the button?

The settings button?

**Comment by EhabxAlaa** [comment] 2023-06-10 22:08
And what is ctrl dev anyway

**Comment by xafn** [comment] 2023-06-10 22:13
Able to reproduce, disable Block Scripts under Brave Shield to fix your issues, JavaScript is required for the website to work.

**Comment by Ushie** [comment] 2023-06-10 22:13
sorry, I meant control + alt + i, for dev tools

**Comment by Ushie** [comment] 2023-06-10 22:14
> Able to reproduce, disable Block Scripts under Brave Shield to fix your issues, JavaScript is required for the website to work.

I don't understand why a lot of browsers sell disabling scripts as a feature, user probably don't even understand what it actually does, seems annoying

**Comment by EhabxAlaa** [comment] 2023-06-10 22:16
> Able to reproduce, disable Block Scripts under Brave Shield to fix your issues, JavaScript is required for the website to work.

Wasn't even on and it doesn't work regardless

**Comment by EhabxAlaa** [comment] 2023-06-10 22:17
> sorry, I meant control + alt + i, for dev tools

And that doesn't do anything

**Comment by xafn** [comment] 2023-06-10 22:17
Well JavaScript is being blocked somehow, was able to reproduce all the issues you had

**Comment by EhabxAlaa** [comment] 2023-06-10 22:20
> Well JavaScript is being blocked somehow, was able to reproduce all the issues you had

Great i can go study now but disabling block scripts didn't fix it as it wasn't on anyway , but disabling brave AdBlock as a whole fixes all issues

**Comment by PalmDevs** [comment] 2023-06-10 22:21
> > Well JavaScript is being blocked somehow, was able to reproduce all the issues you had
> 
> Great i can go study now but disabling block scripts didn't fix it as it wasn't on anyway , but disabling brave AdBlock as a whole fixes all issues

What about other browsers?

**Comment by EhabxAlaa** [comment] 2023-06-10 22:21
> > > Well JavaScript is being blocked somehow, was able to reproduce all the issues you had
> > 
> > 
> > Great i can go study now but disabling block scripts didn't fix it as it wasn't on anyway , but disabling brave AdBlock as a whole fixes all issues
> 
> What about other browsers?

I will test that

**Comment by oSumAtrIX** [comment] 2023-06-10 22:22
You said this issue was happening on Chrome, but chrome does not have any of these blocking features, attach a recording of the issue on Chrome.

**Comment by EhabxAlaa** [comment] 2023-06-10 22:23
> > > Well JavaScript is being blocked somehow, was able to reproduce all the issues you had
> > 
> > 
> > Great i can go study now but disabling block scripts didn't fix it as it wasn't on anyway , but disabling brave AdBlock as a whole fixes all issues
> 
> What about other browsers?

Disabling AdBlock completely on Samsung browser didn't fix the menu button not working for home page

**Comment by EhabxAlaa** [comment] 2023-06-10 22:24
> You said this issue was happening on Chrome, but chrome does not have any of these blocking features, attach a recording of the issue on Chrome.

Sure🥲

**Comment by EhabxAlaa** [comment] 2023-06-10 22:31
I can't upload it for some reason is there a size limit? 
It is only 14 mb

**Comment by EhabxAlaa** [comment] 2023-06-10 22:39
The screen recording refuses to be uploaded, i can't do anything to fix it

**Comment by EhabxAlaa** [comment] 2023-06-10 22:43
https://github.com/revanced/revanced-website/assets/120474122/7ae7e859-17a7-4ae8-a145-a88fa3b67239

Here is a trash version, and it seems like there is a size limit

**Comment by EhabxAlaa** [comment] 2023-06-10 22:50
So brave on mobile is the only browser i was able to get to work fully without any issues after completely disabling AdBlock , but the pc version the settings button didn't work even after disabling AdBlock

**Comment by EhabxAlaa** [comment] 2023-06-10 22:56
So it seems like the home page is cursed since the settings button works on any other page when AdBlock is on or off for pc

**Comment by oSumAtrIX** [comment] 2023-06-10 23:09
Visit this link in Chrome: https://releases.revanced.app/docs. Does it work?

**Comment by EhabxAlaa** [comment] 2023-06-10 23:11
> Visit this link in Chrome: https://releases.revanced.app/docs. Does it work?

Nope, this was on chrome 
![Screenshot_2023-06-11-02-11-28-316_com android chrome](https://github.com/revanced/revanced-website/assets/120474122/909056b3-eafe-4046-bee9-4028696a3a57)

**Comment by EhabxAlaa** [comment] 2023-06-10 23:26
I want to understand something and please reply to it 
Are you testing on your side and can't reproduce the issue on your chrome, and that is why you are asking me to test and record?

**Comment by oSumAtrIX** [comment] 2023-06-10 23:34
Seems like your network is blocking the domain. Use a custom domain and try again.

**Comment by EhabxAlaa** [comment] 2023-06-10 23:36
> Seems like your network is blocking the domain. Use a custom DNS and try again.

How do i do that? Please reply quickly

**Comment by EhabxAlaa** [comment] 2023-06-10 23:37
> Seems like your network is blocking the domain. Use a custom DNS and try again.

What do i write here or is that wrong? 
![Screenshot_2023-06-11-02-37-01-101_com android settings](https://github.com/revanced/revanced-website/assets/120474122/172cd04f-a453-4b25-ba7f-a72ed3b199ed)

**Comment by EhabxAlaa** [comment] 2023-06-10 23:42
Can we end my part in this 15 minutes?  as i will go sleep and won't reply for a day

**Comment by oSumAtrIX** [comment] 2023-06-10 23:54
You can enter 1.1.1.1 for example

**Comment by EhabxAlaa** [comment] 2023-06-10 23:57
Doesn't work can't even enter it 
![Screenshot_2023-06-11-02-56-26-651_com android settings](https://github.com/revanced/revanced-website/assets/120474122/ee13a3ff-0a09-448d-8deb-82d89c13bd3b)

**Comment by EhabxAlaa** [comment] 2023-06-10 23:57
And if it was longer i get cannot connect

**Comment by EhabxAlaa** [comment] 2023-06-10 23:59
I will go sleep, we can continue tomorrow if i had time as i have an exam soon in a subject i haven't opened for a month, please try to test on your side instead

**Comment by oSumAtrIX** [comment] 2023-06-11 00:02
You can use a vpn, it has the same effect, closing as it is assumed to be an issue with your DNS, reopen when confirmed it isn't

**Closed by oSumAtrIX** 2023-06-11 00:02 UTC
Labels: question

**Comment by EhabxAlaa** [comment] 2023-06-11 00:09
> You can use a vpn, it has the same effect, closing as it is assumed to be an issue with your DNS, reopen when confirmed it isn't

VPN fixed nothing neither the link or the website 
![Screenshot_2023-06-11-03-06-03-662_com android chrome](https://github.com/revanced/revanced-website/assets/120474122/edf5c93e-c547-4927-b73d-f3dde8a6fb0f)
As you see i used VPN at the top

**Comment by EhabxAlaa** [comment] 2023-06-11 00:11
Also other devs said that they can reproduce, and call it my internet problem for some weird reason 😑

**Comment by EhabxAlaa** [comment] 2023-06-11 00:12
I really am not interested in the website so i won't open others issues since i provided enough info

**Comment by Ushie** [comment] 2023-06-11 00:14
> Also other devs said that they can reproduce, and you call it my internet problem for some weird reason 😑

The other dev was only able to reproduce by disabling Javascript, breaking websites entirely is expected when you disable the thing that makes most of the website, you said you didn't have Javascript blocked

**Comment by EhabxAlaa** [comment] 2023-06-11 00:15
> > Also other devs said that they can reproduce, and you call it my internet problem for some weird reason 😑
> 
> The other dev was only able to reproduce by disabling Javascript, breaking websites entirely is expected when you disable the thing that makes most of the website, you said you didn't have Javascript blocked

JavaScript was enabled on all browsers what do you mean?!

**Comment by Ushie** [comment] 2023-06-11 00:16
What I meant is, no, the other developer wasn't able to reproduce your situation under the same conditions

**Comment by EhabxAlaa** [comment] 2023-06-11 00:16
So it isn't a JavaScript problem here

**Comment by EhabxAlaa** [comment] 2023-06-11 00:19
> What I meant is, no, the other developer wasn't able to reproduce your situation under the same conditions

Oh i get it now , but whatever i will go sleep

**Comment by EhabxAlaa** [comment] 2023-06-11 00:26
One last thing that confirms that it isn't my internet is that i was able to get the website to work 100% on brave after disabling AdBlock, so what else could it be?

**Comment by PalmDevs** [comment] 2023-06-11 10:54
> So it isn't a JavaScript problem here

Correct, it's an issue on your end. Your device can't load our website's JavaScript properly.

**Comment by EhabxAlaa** [comment] 2023-06-11 10:56
> > So it isn't a JavaScript problem here
> 
> Correct, it's an issue on your end. Your device can't load our website's JavaScript properly.

What may cause that is never seem to have any problem with other websites?!

**Comment by EhabxAlaa** [comment] 2023-06-11 11:25
I tried the website on my Samsung tablet using Samsung browser and i had all issues that could exist and that existed on chrome and other browser, i lost hope in understanding what may cause that so i will stop testing unless you guys show interest in this issue as i already wasted 4 hours yesterday and then my issue was closed , so i am a bit upset that all that time was wasted for nothing at the end for an issue in a website that i don't need since i just use github

**Comment by PalmDevs** [comment] 2023-06-11 11:59
> > > So it isn't a JavaScript problem here
> > 
> > Correct, it's an issue on your end. Your device can't load our website's JavaScript properly.
> 
> What may cause that ? as i  never seem to have any problem with other websites?! 

Your provider or router may be the issue, it may have been configured to block newly registered websites or "suspicious" websites, but it seems to load everything fine except JS. A custom DNS server may be the cause as well, but you don't seem to be using it. Maybe try `1dot1dot1dot1.cloudflare-dns.com` as your custom DNS server (can be configured in your phone settings).

**Comment by EhabxAlaa** [comment] 2023-06-11 12:05
> > > > So it isn't a JavaScript problem here
> > > 
> > > 
> > > Correct, it's an issue on your end. Your device can't load our website's JavaScript properly.
> > 
> > 
> > What may cause that ? as i  never seem to have any problem with other websites?!
> 
> Your provider or router may be the issue, it may have been configured to block newly registered websites or "suspicious" websites, but it seems to load everything fine except JS. A custom DNS server may be the cause as well, but you don't seem to be using it. Maybe try `1dot1dot1dot1.cloudflare-dns.com` as your custom DNS server (can be configured in your phone settings).

I tried it and it connected but the menu button and settings button doesn't work on home page still

**Comment by oSumAtrIX** [comment] 2023-06-11 12:48
Attach a recording that shows that you changed the DNS and visit the page releases.revanced.app

**Comment by EhabxAlaa** [comment] 2023-06-11 12:53
> 

Like this? 

https://github.com/revanced/revanced-website/assets/120474122/696d3d9e-e1d0-4bac-b8bd-3789669ccc71

**Comment by oSumAtrIX** [comment] 2023-06-11 13:59
Restart the browser, it probably takes a while to update the DNS settings

**Comment by EhabxAlaa** [comment] 2023-06-11 14:04
> Restart the browser, it probably takes a while to update the DNS settings

Did that and waited for a few minutes and still a while blank page

**Comment by oSumAtrIX** [comment] 2023-06-11 14:07
This is an issue with your device or network connection, check on another device on the same network and check on another device on a different network.

**Comment by EhabxAlaa** [comment] 2023-06-11 14:10
We can end this now , if you think it only happens to me and works fine for everyone else then it is not wroth fixing, as i can use github instead, thanks for all of guys time i may reopen this after my exam since i am curious to know what causes this

**Comment by EhabxAlaa** [comment] 2023-06-11 14:11
> This is an issue with your device or network connection, check on another device on the same network and check on another device on a different network.

I checked on my Samsung tablet and all issues exist but it is fine it is not worth fixing

**Comment by oSumAtrIX** [comment] 2023-06-11 14:19
> I checked on my Samsung tablet and all issues exist

Check on a different network as previously asked

**Comment by EhabxAlaa** [comment] 2023-06-11 14:20
> This is an issue with your device or network connection, check on another device on the same network and check on another device on a different network.

Why couldn't you think of " try mobile data "?! 

I tried using mobile data and it worked perfectly 😂😂

**Comment by EhabxAlaa** [comment] 2023-06-11 14:22
> 

The website is fully functional with mobile data , so it was my WiFi after all  despite trying different DNS and vpn
